CREATE TABLE HOMOLOG_CONTAINER (
	NCONTAINER VARCHAR(50),
	DTCAD DATETIME,
	NUMSERIE VARCHAR(50),
	MODELO1 VARCHAR(50),
	MODELO2 VARCHAR(50),
	TIPOALT VARCHAR(10),
	GRAVACÃO VARCHAR(10),
	TIPO VARCHAR(10),
	VEND_COMP VARCHAR(10)
)